#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-contacts
Version  : 3.36.2
Release  : 8
URL      : https://download.gnome.org/sources/gnome-contacts/3.36/gnome-contacts-3.36.2.tar.xz
Source0  : https://download.gnome.org/sources/gnome-contacts/3.36/gnome-contacts-3.36.2.tar.xz
Summary  : A library full of GTK widgets for mobile phones
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-2.1+
Requires: gnome-contacts-bin = %{version}-%{release}
Requires: gnome-contacts-data = %{version}-%{release}
Requires: gnome-contacts-lib = %{version}-%{release}
Requires: gnome-contacts-libexec = %{version}-%{release}
Requires: gnome-contacts-license = %{version}-%{release}
Requires: gnome-contacts-locales = %{version}-%{release}
Requires: gnome-contacts-man = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : folks-dev
BuildRequires : gnome-desktop-dev
BuildRequires : gnome-online-accounts-dev
BuildRequires : libhandy-dev
BuildRequires : pkgconfig(cheese)
BuildRequires : pkgconfig(folks)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(goa-1.0)

%description
# GNOME Contacts
Contacts organizes your contacts information from all your online and offline
sources, providing a centralized place for managing your contacts.

%package bin
Summary: bin components for the gnome-contacts package.
Group: Binaries
Requires: gnome-contacts-data = %{version}-%{release}
Requires: gnome-contacts-libexec = %{version}-%{release}
Requires: gnome-contacts-license = %{version}-%{release}

%description bin
bin components for the gnome-contacts package.


%package data
Summary: data components for the gnome-contacts package.
Group: Data

%description data
data components for the gnome-contacts package.


%package dev
Summary: dev components for the gnome-contacts package.
Group: Development
Requires: gnome-contacts-lib = %{version}-%{release}
Requires: gnome-contacts-bin = %{version}-%{release}
Requires: gnome-contacts-data = %{version}-%{release}
Provides: gnome-contacts-devel = %{version}-%{release}
Requires: gnome-contacts = %{version}-%{release}

%description dev
dev components for the gnome-contacts package.


%package lib
Summary: lib components for the gnome-contacts package.
Group: Libraries
Requires: gnome-contacts-data = %{version}-%{release}
Requires: gnome-contacts-libexec = %{version}-%{release}
Requires: gnome-contacts-license = %{version}-%{release}

%description lib
lib components for the gnome-contacts package.


%package libexec
Summary: libexec components for the gnome-contacts package.
Group: Default
Requires: gnome-contacts-license = %{version}-%{release}

%description libexec
libexec components for the gnome-contacts package.


%package license
Summary: license components for the gnome-contacts package.
Group: Default

%description license
license components for the gnome-contacts package.


%package locales
Summary: locales components for the gnome-contacts package.
Group: Default

%description locales
locales components for the gnome-contacts package.


%package man
Summary: man components for the gnome-contacts package.
Group: Default

%description man
man components for the gnome-contacts package.


%prep
%setup -q -n gnome-contacts-3.36.2
cd %{_builddir}/gnome-contacts-3.36.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600273181
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-contacts
cp %{_builddir}/gnome-contacts-3.36.2/COPYING %{buildroot}/usr/share/package-licenses/gnome-contacts/2c026582eb07be6897378e91a8c8c76fee512d72
cp %{_builddir}/gnome-contacts-3.36.2/subprojects/libhandy/COPYING %{buildroot}/usr/share/package-licenses/gnome-contacts/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/gnome-contacts-3.36.2/subprojects/libhandy/debian/copyright %{buildroot}/usr/share/package-licenses/gnome-contacts/d295f3a9ec2407b00d9f397ce11fb432ae071dd2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-contacts

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-contacts

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Handy-0.0.typelib
/usr/share/applications/org.gnome.Contacts.desktop
/usr/share/dbus-1/services/org.gnome.Contacts.SearchProvider.service
/usr/share/dbus-1/services/org.gnome.Contacts.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.Contacts.gschema.xml
/usr/share/gnome-shell/search-providers/org.gnome.Contacts.search-provider.ini
/usr/share/icons/hicolor/scalable/apps/org.gnome.Contacts.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Contacts.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Contacts-symbolic.svg
/usr/share/metainfo/org.gnome.Contacts.appdata.xml
/usr/share/vala/vapi/libhandy-0.0.deps
/usr/share/vala/vapi/libhandy-0.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libhandy-0.0/handy.h
/usr/include/libhandy-0.0/hdy-action-row.h
/usr/include/libhandy-0.0/hdy-animation.h
/usr/include/libhandy-0.0/hdy-arrows.h
/usr/include/libhandy-0.0/hdy-column.h
/usr/include/libhandy-0.0/hdy-combo-row.h
/usr/include/libhandy-0.0/hdy-deprecation-macros.h
/usr/include/libhandy-0.0/hdy-dialer-button.h
/usr/include/libhandy-0.0/hdy-dialer-cycle-button.h
/usr/include/libhandy-0.0/hdy-dialer.h
/usr/include/libhandy-0.0/hdy-dialog.h
/usr/include/libhandy-0.0/hdy-enum-value-object.h
/usr/include/libhandy-0.0/hdy-enums.h
/usr/include/libhandy-0.0/hdy-expander-row.h
/usr/include/libhandy-0.0/hdy-fold.h
/usr/include/libhandy-0.0/hdy-header-bar.h
/usr/include/libhandy-0.0/hdy-header-group.h
/usr/include/libhandy-0.0/hdy-keypad.h
/usr/include/libhandy-0.0/hdy-leaflet.h
/usr/include/libhandy-0.0/hdy-list-box.h
/usr/include/libhandy-0.0/hdy-main.h
/usr/include/libhandy-0.0/hdy-paginator.h
/usr/include/libhandy-0.0/hdy-preferences-group.h
/usr/include/libhandy-0.0/hdy-preferences-page.h
/usr/include/libhandy-0.0/hdy-preferences-row.h
/usr/include/libhandy-0.0/hdy-preferences-window.h
/usr/include/libhandy-0.0/hdy-search-bar.h
/usr/include/libhandy-0.0/hdy-squeezer.h
/usr/include/libhandy-0.0/hdy-string-utf8.h
/usr/include/libhandy-0.0/hdy-swipe-group.h
/usr/include/libhandy-0.0/hdy-swipeable.h
/usr/include/libhandy-0.0/hdy-title-bar.h
/usr/include/libhandy-0.0/hdy-value-object.h
/usr/include/libhandy-0.0/hdy-version.h
/usr/include/libhandy-0.0/hdy-view-switcher-bar.h
/usr/include/libhandy-0.0/hdy-view-switcher.h
/usr/lib64/libhandy-0.0.so
/usr/lib64/pkgconfig/libhandy-0.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhandy-0.0.so.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gnome-contacts-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-contacts/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gnome-contacts/2c026582eb07be6897378e91a8c8c76fee512d72
/usr/share/package-licenses/gnome-contacts/d295f3a9ec2407b00d9f397ce11fb432ae071dd2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnome-contacts.1

%files locales -f gnome-contacts.lang
%defattr(-,root,root,-)

